spring:
  datasource:
    url: jdbc:postgresql://www.hellmiao.com:5432/miao_home
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

storage:
  type: aliyun
  aliyun:
    endpoint: ${STORAGE_ALIYUN_ENDPOINT:}
    region: ${STORAGE_ALIYUN_REGION:}
    bucket: ${STORAGE_ALIYUN_BUCKET:}
    access-key-id: ${STORAGE_ALIYUN_ACCESS_KEY_ID:}
    access-key-secret: ${STORAGE_ALIYUN_ACCESS_KEY_SECRET:}
    role-arn: ${STORAGE_ALIYUN_ROLE_ARN:}
    role-session-name: ${ALIYUN_OSS_ROLE_SESSION_NAME:miaohome}

# 生产环境关闭 Swagger 接口文档
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: warn
    com.miaohome: info
